#!/usr/bin/env bash
# prints "fizz" and "buzz" for moduli of 3 and 5 respectively and "FizzBuzz" for both

i = 1;
 while [ "$i" -le 100 ]; do
	if [ "$i" % 3 == 0 ]; then
		echo "Fizz"
	elif [ "$i" % 5 == 0 ]; then
		echo "Buzz"
	elif [ "$i" % 3 == 0 && "$i" % 5 == 0 ]; then
		echo "FizzBuzz"
	else
		 echo "$i"
fi
	((i++))
done
