#!/usr/bin/env bash
# prints 3 different  strings in the program

i = 1;
while [ "$i" -lt 11 ]; do
 
if [ "$i" -eq 4 ]; then
 echo "bad luck"
elif [ "$i" -eq 8 ]; then
 echo "good luck"
else
 echo "Best school"
fi

 ((i++))
done
